# Generated by Django 5.0.6 on 2024-07-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_comment_discountproduct_dislike_likeproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('added_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
